### ISSUE TITLE
Consider the use of FieldArrayType

### ISSUE THREAD

**Issue by skounis** [skounis/ng2-firefront#22]
Based on the review left:
- https://github.com/skounis/ng2-firefront/pull/21#pullrequestreview-109910813

**Comment by skounis** [comment]
@genna Could we check this suggestion. Should we try it?

**Comment by genna** [comment]
@skounis It's not possible to use `FieldArrayType` for master/details control since we don't remove an item from list immediately but just mark it as deleted. We use very custom approach for that
