### ISSUE TITLE
Enable the color property of material 

### ISSUE THREAD

**Issue by skounis** [skounis/ng2-firefront#50]
It seems that the `color` property of material is not taken into account

- https://www.screencast.com/t/slPjtkuXU

We should check why this happens and if it is fixable.

**Comment by tkumpanenko** [comment]
`mat-icon-button` missing directive for button 

https://github.com/skounis/ng2-firefront/pull/53/commits/d1634cfd2d7ea410cdca3f4340253823a2043716 - fixed here
