### ISSUE TITLE
Configure Formly to use MD style for Input and Textarea

### ISSUE THREAD

**Issue by skounis** [skounis/ng2-firefront#68]
We should change the style used for the text input and textarea controls to Material 

- https://www.screencast.com/t/594q7Ohlpyw9

**Comment by tkumpanenko** [comment]
Do you want to get rid bootstap at all?

**Comment by skounis** [comment]
That's the goal but I'm not sure if this will work. Last time we tried that
we decided to roll back to bootstrap.

That's why I suggested to work only on input and text area. I have no
strong though. If you prefer to configure the whole Formly to work with MD
and then test the results, that's also fine.
