### ISSUE TITLE
Create an additional listing screen for for records by using tables 

### ISSUE THREAD

**Issue by skounis** [skounis/ng2-firefront#69]
Currently we use the `/manager/businesses` path for listing the records for the related collection (eg `businesses`

We should provide an additional screen where the same functionality will be provided by using Tables. 

- https://www.screencast.com/t/vxf6leaqhhoJ

We could use a separate URI for this purpose eg `/manager/businesses/table`

**Comment by tkumpanenko** [comment]
@skounis we also need some links/toogler in toolbar to change view mode

**Comment by skounis** [comment]
That's an even better idea. Would you like to implement it like this?

In this case is seems that we do not need separate paths in the URL, right?

**Comment by tkumpanenko** [comment]
We will keep this state in store or localstorage, and we can even extend formly config with "defaultListView" : "table" // "grid"
